### ISSUE TITLE
The Shadow / Explode Moving

### ISSUE THREAD

**Issue by DHStyle541** [OnionMilk-Mods/crawlingmine#2]
Hi i found bug when Landmine already Explode but the shadow / explode moving

![image](https://github.com/OnionMilk-Mods/crawlingmine/assets/154591650/aff48a62-d360-42a0-9044-8dc4abb8458c)

![image](https://github.com/OnionMilk-Mods/crawlingmine/assets/154591650/1469e45a-fd82-4007-99b2-71cd6a5dbc62)

and Log Spam when 100% crawling mines

**Comment by zbigniewcebula** [comment]
I'm on it!

Can you show me more about `Log Spam`?

**Comment by DHStyle541** [comment]
Log spam occurs when 100% CrawlingMine.
I can't provide logs because I have set CrawlingMines chance to 5% so there is no log spam. this only happens if there is a 100% chance of crawling the mine

If you want, you can test at the HullBreaker Company, because they have a Landmine Event

**Comment by zbigniewcebula** [comment]
Okay, update done, Log turned off. I assume you meant "Jumped!" logs. Also shadows and "blow" should not move after explosion :)
[#1.0.4](https://github.com/OnionMilk-Mods/crawlingmine/releases/tag/1.0.4)

**Comment by DHStyle541** [comment]
Tq 👍
