### ISSUE TITLE
HarmonyX error

### ISSUE THREAD

**Issue by darkbrewery** [OnionMilk-Mods/crawlingmine#3]
After updating to the new version I get this on loading

![image](https://github.com/OnionMilk-Mods/crawlingmine/assets/806316/f374f748-aeab-4c9d-ae29-be9ebc0ade05)

**Comment by zbigniewcebula** [comment]
Okay, I gonna check this now!

**Comment by zbigniewcebula** [comment]
Fixed https://github.com/OnionMilk-Mods/crawlingmine/releases/tag/1.0.6

**Comment by darkbrewery** [comment]
Beauty! Will test later, haven't actually witnessed and mines moving yet, but will report back
